[package]
name = "zed_astro"
version = "0.1.7"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/astro.rs"
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
zed_extension_api = "0.7.0"
